Human Activity Recognition

```{r, warning=FALSE}
library(caret)
library(data.table)

training <- fread("pml-training.csv")
testing <- fread("pml-testing.csv")
```

*Tidying Data*
```{r, cache=TRUE}
trainingPrime <- t(na.omit(t(training)))
trainingPrime <- trainingPrime[, -c(1:7)]
toDrop <- c("^kurtosis*","^skewness*","yaw")
trainingPrime <- trainingPrime[, -grep(paste(toDrop, collapse = "|"),
                                       colnames(trainingPrime))]
trainingPrime <- as.data.table(trainingPrime)
```
```{r}
trainingPrime[,1:48] <- trainingPrime[, lapply(trainingPrime[,1:48], as.numeric)]
trainingPrime$classe <- as.factor(trainingPrime$classe)
dim(trainingPrime)
```


*First Cross Validation - Random Forest*
```{r}
inTrain <- createDataPartition(y=trainingPrime$classe,
                               p=.75, list=FALSE)
training1 <- trainingPrime[inTrain,]
testing1 <- trainingPrime[-inTrain,]
```
*Model 1: Random Forest; recommended defaults*
```{r}
#Configur parallel processing
start.time <- Sys.time()
library(parallel)
library(doParallel)
library(randomForest)

cluster <- makeCluster(detectCores()-1)
registerDoParallel(cluster)

#Recommended default control features
fitControl <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 3,
                           allowParallel = TRUE)

set.seed(1704111)
fitRF1 <- train(classe~., data=training1, 
                method="rf", 
                metric = "Accuracy", 
                trControl = fitControl, 
                tuneGrid = expand.grid(mtry=7))

stopCluster(cluster)
registerDoSEQ()
end.time <- Sys.time()
time.takenRF1 <- end.time - start.time #Time difference of 8.76054 mins
fitRF1
```
- fitRF1: Resample, confustion matrix
```{r}
fitRF1$resample
```
```{r}
confusionMatrix(fitRF1)
```





*Model 2: Random Forest; search = "random"*
```{r}
#Configur parallel processing
start.time <- Sys.time()
library(parallel)
library(doParallel)
library(randomForest)

cluster <- makeCluster(detectCores()-1)
registerDoParallel(cluster)

#search = "random"
fitControl <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 3,
                           search = "random",
                           allowParallel = TRUE)

set.seed(1704111)
fitRF2 <- train(classe~., data=training1, 
                method="rf", 
                metric = "Accuracy", 
                trControl = fitControl, 
                tuneLength = 15)

stopCluster(cluster)
registerDoSEQ()
end.time <- Sys.time()
time.takenRF2 <- end.time - start.time
fitRF2
```







```{r}
start.time <- Sys.time()
library(parallel)
library(doParallel)
cluster <- makeCluster(detectCores()-1)
registerDoParallel(cluster)

inTrain2 <- createDataPartition(y=trainingPrime$classe,
                               p=.75, list=FALSE)
training2 <- trainingPrime[inTrain2,]
testing2 <- trainingPrime[-inTrain2,]

gbmGrid <- expand.grid(shrinkage = .1,
                       n.trees = (1:30)*50,
                       interaction.depth = c(1,5,9),
                       n.minobsinnode = 20)

fitControl2 <- trainControl(method = "cv",
                            number = 10,
                            allowParallel = TRUE)
set.seed(1704112)
fit2 <- train(classe~., data=training2,
              method="gbm", trControl = fitControl2,
              verbose=FALSE, tuneGrid=gbmGrid)
stopCluster(cluster)
registerDoSEQ()
end.time <- Sys.time()
time.taken <- end.time - start.time
fit2

```


*Applying randomForest model to testing set*
```{r}
pred1 <- predict(fit1, testing1)
testing1$predRight <- pred1 == testing1$classe
table(pred1, testing1$classe)
```
```{r}
sum(testing1$predRight)/length(testing1$classe)
```

